version: '3.7'

services:

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONOGO_INITDB_DATABASE: wirvonhier
    container_name: 'wirvonhier-mongo'
    volumes:
      - ./mongo_volume:/data/db
      - ./mongo-seed/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017-27019:27017-27019

  # To seed the DB
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin 
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
