/* eslint-disable @typescript-eslint/camelcase */
const upload = {
  uri: '/videos/436144868',
  name: 'Test Title',
  description: 'Test Desc',
  type: 'video',
  link: 'https://vimeo.com/436144868/aa98dc855f',
  duration: 0,
  width: 400,
  language: null,
  height: 300,
  embed: {
    buttons: {
      like: true,
      watchlater: true,
      share: true,
      embed: true,
      hd: false,
      fullscreen: true,
      scaling: true,
    },
    logos: { vimeo: true, custom: [Object] },
    title: { name: 'user', owner: 'user', portrait: 'user' },
    playbar: true,
    volume: true,
    speed: false,
    color: '00adef',
    uri: null,
    html:
      '<iframe src="https://player.vimeo.com/video/436144868?title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=173890" width="400" height="300" frameborder="0" allow="autoplay; fullscreen" allowfullscreen title="Test Title"></iframe>',
    badges: {
      hdr: false,
      live: [Object],
      staff_pick: [Object],
      vod: false,
      weekend_challenge: false,
    },
  },
  created_time: '2020-07-07T16:19:22+00:00',
  modified_time: '2020-07-07T16:19:22+00:00',
  release_time: '2020-07-07T16:19:22+00:00',
  content_rating: ['unrated'],
  license: null,
  privacy: {
    view: 'unlisted',
    embed: 'public',
    download: true,
    add: true,
    comments: 'anybody',
  },
  pictures: {
    uri: null,
    active: false,
    type: 'default',
    sizes: [[Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object]],
    resource_key: '7a491d0e8cad256a8ac2fd6d207e647c1b034bad',
  },
  tags: [],
  stats: { plays: 0 },
  categories: [],
  metadata: {
    connections: {
      comments: [Object],
      credits: null,
      likes: [Object],
      pictures: [Object],
      texttracks: [Object],
      related: null,
      recommendations: null,
      albums: [Object],
      available_albums: [Object],
      versions: [Object],
    },
    interactions: { watchlater: [Object], report: [Object] },
  },
  user: {
    uri: '/users/113839103',
    name: 'Kevin Bein',
    link: 'https://vimeo.com/user113839103',
    location: '',
    gender: '',
    bio: null,
    short_bio: null,
    created_time: '2020-04-25T17:18:06+00:00',
    pictures: {
      uri: null,
      active: false,
      type: 'default',
      sizes: [Array],
      resource_key: '06cd312fcc3908e2d839aeb00ccaaf434acb0859',
    },
    websites: [],
    metadata: { connections: [Object] },
    location_details: {
      formatted_address: '',
      latitude: null,
      longitude: null,
      city: null,
      state: null,
      neighborhood: null,
      sub_locality: null,
      state_iso_code: null,
      country: null,
      country_iso_code: null,
    },
    skills: [],
    available_for_hire: false,
    can_work_remotely: false,
    preferences: { videos: [Object] },
    content_filter: ['language', 'drugs', 'violence', 'nudity', 'safe', 'unrated'],
    upload_quota: { space: [Object], periodic: [Object], lifetime: [Object] },
    resource_key: '514922dec748a6c1f2a8296b4217f2eeca619097',
    account: 'pro',
  },
  review_page: {
    active: true,
    link: 'https://vimeo.com/user113839103/review/436144868/157d644897',
  },
  parent_folder: null,
  last_user_action_event_date: '2020-07-07T16:19:22+00:00',
  files: [],
  download: [],
  app: { name: 'WirVonHier', uri: '/apps/173890' },
  status: 'uploading',
  resource_key: '72f07b89b75b487a249d6ca773a4c7d05589901c',
  upload: {
    status: 'in_progress',
    upload_link: 'https://europe-files.tus.vimeo.com/files/vimeo-prod-src-tus-eu/b25c0f2a2a694cbdbeeb24dff9f0910b',
    form: null,
    complete_uri: null,
    approach: 'tus',
    size: 208288,
    redirect_url: null,
    link: null,
  },
  transcode: { status: 'in_progress' },
};
