name: Release - Server - Test, Build & Redeploy

on:
  push:
    branches:
      - 'release-*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12.18.2-alpine3.12

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install # should run npm run test next
  
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t server .
        
      - name: Tags
        run: |
          now=$(date)
          docker tag server ${{ secrets.DOCKER_ORGANIZATION }}/server:release-$now
          docker tag server ${{ secrets.DOCKER_ORGANIZATION }}/server:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_ORGANIZATION }}/server:release-$now
          docker push ${{ secrets.DOCKER_ORGANIZATION }}/server:latest
