name: Test - Server - Test, Build & Delploy on test.wirvonhier.net

on:
  push:
    branches:
      - 'test'

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:12.18.2-alpine3.12

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Install dependencies
  #     run: npm install # should run npm run test next
  
  # docker:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Docker Login
  #       run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build Image
  #       run: docker build -t server .

  #     - name: Tag Image
  #       run: |
  #         docker tag server ${{ secrets.DOCKER_ORGANIZATION }}/server:test-${{ github.sha }}

  #     - name: Push Image
  #       run: |
  #         docker push ${{ secrets.DOCKER_ORGANIZATION }}/server:test-${{ github.sha }}

  redeploy: # need to update secrets on server just to make sure they are up-to-date
    runs-on: ubuntu-latest
    # needs: docker
    steps:
      - uses: actions/checkout@v2

      - name: Install Open SSH
        run: sudo apt-get update && sudo apt-get install openssh-client

      - name: SET ssh keys
        run: |
          mkdir "$HOME/.ssh"
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          eval $(ssh-agent)
          ssh-add "$HOME/.ssh/id_rsa"
          printf '%s %s\n' "${{ secrets.DOCKER_HOST }}" "${{ secrets.SSH_PUBLIC_KEY }}" > "$HOME/.ssh/ssh_known_hosts"

      # - name: Set Docker Remote Context
      #   run: docker context create wirvonhier --default-stack-orchestrator=swarm --docker "host=ssh://${{ secrets.DOCKER_HOST_USER }}@${{ secrets.DOCKER_HOST }}"
      - name: Set Docker Remote Context
        run: docker context create wirvonhier --default-stack-orchestrator=swarm --docker "host=ssh://wvh@185.185.26.56"

      - name: TEST Remote
        run: docker --context wirvonhier image ls

      # - name: Update Docker Secrets
      #   run: |
      #     echo "${{ secrets.MONGO_USER }} | docker --context wirvonhier secret create mongo_user -
      #     echo "${{ secrets.MONGO_PASSWORD }} | docker --context wirvonhier secret create mongo_password -
      #     echo "${{ secrets.SENDGRID_API_KEY }} | docker --context wirvonhier secret create sendgrid_api_key -
      #     echo "${{ secrets.CLOUDINARY_API_KEY }} | docker --context wirvonhier secret create cloudinary_api_key -
      #     echo "${{ secrets.CLOUDINARY_API_SECRET }} | docker --context wirvonhier secret create cloudinary_api_secret -
      #     echo "${{ secrets.VIMEO_ACCESS_TOKEN }} | docker --context wirvonhier secret create vimeo_access_token -
      #     echo "${{ secrets.GOOGLE_MAPS_API_KEY }} | docker --context wirvonhier secret create google_maps_api_key -

      # - name: Update Service
      #   run: docker service update server_test # HOW to get right image tag?
